//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nXs.Web.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class FichaClientes
    {
        public int Id { get; set; }
        public int ClienteId { get; set; }
        public Nullable<bool> Activo { get; set; }
        public string Edad { get; set; }
        public string Altura { get; set; }
        public string Peso { get; set; }
        public string GrupoSanguineo { get; set; }
        public Nullable<bool> PColumna { get; set; }
        public string DetalleColumna { get; set; }
        public Nullable<bool> ECardiaca { get; set; }
        public string DetalleCardiaca { get; set; }
        public Nullable<bool> LRecientes { get; set; }
        public string DetalleLesion { get; set; }
        public Nullable<bool> Deportes { get; set; }
        public string DetalleDeporte { get; set; }
        public string Observacion { get; set; }
        public string ObjPersonal { get; set; }
        public Nullable<int> UserId { get; set; }
        public string CreateDate { get; set; }
        public string DeleteDate { get; set; }
        public string UpdateDate { get; set; }
    }
}
